<?php

include_once 'masterprint_admin.features.inc';

/**
 * Implements hook_menu()
 */
function masterprint_admin_menu() {
  $items = array();
  $items['user/%user/admin'] = array(
    'title' => '管理员管理',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'masterprint_admin_access',
    'access arguments' => array(1),
    'page callback' => 'masterprint_admin_load_managed_admin',
    'page arguments' => array(1),
    'weight' => '100',
  );
  $items['user/%user/admin/list'] = array(
    'title' => '管理员列表',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => '-10',
  );
  $items['user/%user/admin/add'] = array(
    'title' => '添加管理员',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'masterprint_admin_access',
    'access arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('masterprint_admin_add_admin_form', 1),
  );
  return $items;
}

/**
 * Access callback
 */
function masterprint_admin_access($user) {
  if ($user->uid == '1') return TRUE;

  // @todo We have to limit the admin operation to the super admin user only.
  if (!empty($user->uid) && $user->name == 'admin') {
    return true;
  }
  return false;
}

/**
 * Display a list of all the AEs managed by the current user
 */
function masterprint_admin_load_managed_admin($user) {
  $output = '';
  $output .= views_embed_view('admin_listing', 'created_by_user', $user->uid);
  return $output;
}

/**
 * Form used for adding/editing an AE
 */
function masterprint_admin_add_admin_form($form, &$form_state, $user) {
  $form = array();
  // Append the profile2 AE fields
  $form['account'] = array(
    '#type' => 'fieldset',
    '#title' => t('账户信息'),
  );
  $form['account']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('用户名'),
    '#maxlength' => USERNAME_MAX_LENGTH,
    '#description' => t('Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.'),
    '#required' => TRUE,
    '#attributes' => array('class' => array('username')),
    '#default_value' => '',
  );
  $form['account']['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail地址'),
    '#maxlength' => EMAIL_MAX_LENGTH,
    '#description' => t('A valid e-mail address. All e-mails from the system will be sent to this address. The e-mail address is not made public and will only be used if you wish to receive a new password or wish to receive certain news or notifications by e-mail.'),
    '#required' => TRUE,
    '#default_value' => '',
  );

  // Client's password's randomly generated, not specified by creator
  $form['account']['pass'] = array(
    '#type' => 'value',
    '#value' => user_password(mt_rand(6, 8)),
  );

  // Append the profile2 'admin' fields
  $form['profile_admin'] = array(
    '#type' => 'fieldset',
    '#title' => t('资料信息'),
  );
  $profile = profile_create(array('type' => 'admin'));
  $form_state['profiles']['admin'] = $profile;
  field_attach_form('profile2', $profile, $form['profile_admin'], $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('提交'),
  );

  return $form;
}

/**
 * Validation handler
 */
function masterprint_admin_add_admin_form_validate(&$form, &$form_state) {
  // Validate username.
  if (isset($form_state['values']['name'])) {
    if ($error = user_validate_name($form_state['values']['name'])) {
      form_set_error('name', $error);
    }
    else {
      $duplicate = (bool) db_select('users')
        ->fields('users', array('uid'))
        ->condition('name', db_like($form_state['values']['name']), 'LIKE')
        ->range(0, 1)
        ->execute()
        ->fetchField();

      if ($duplicate) {
        form_set_error('name', t('The name %name is already taken.', array('%name' => $form_state['values']['name'])));
      }
    }
  }

  // Trim whitespace from mail, to prevent confusing 'e-mail not valid'
  // warnings often caused by cutting and pasting.
  $mail = trim($form_state['values']['mail']);
  form_set_value($form['account']['mail'], $mail, $form_state);

  // Validate email
  if ($error = user_validate_mail($form_state['values']['mail'])) {
    form_set_error('mail', $error);
  }
  else {
    $duplicate = (bool) db_select('users')
      ->fields('users', array('uid'))
      ->condition('mail', db_like($form_state['values']['mail']), 'LIKE')
      ->range(0, 1)
      ->execute()
      ->fetchField();

    if ($duplicate) {
      form_set_error('mail', t('The e-mail address %email is already taken.', array('%email' => $form_state['values']['mail'])));
    }
  }

  // Validate profile2 fields
  if (isset($form_state['values']['profile_admin'])) {
    // @see entity_form_field_validate()
    $pseudo_entity = (object) $form_state['values']['profile_admin'];
    $pseudo_entity->type = 'admin';
    field_attach_form_validate('profile2', $pseudo_entity, $form['profile_admin'], $form_state);
  }
}

/**
 * Submission handler
 */
function masterprint_admin_add_admin_form_submit(&$form, &$form_state) {
  global $user;
  $uid = $user->uid;

  // Get the role id of role 'Client'
  $role_name = '管理员';
  $role = user_role_load_by_name($role_name);
  $rid = $role->rid;

  // Build the user object
  $pass = masterprint_admin_generate_admin_password();
  $new_user = array(
    'name' => $form_state['values']['name'],
    'pass' => $pass,
    'mail' => $form_state['values']['mail'],
    'init' => $form_state['values']['mail'],
    'status' => 1,
    'access' => REQUEST_TIME,
    'roles' => array($rid => $role_name),
    'field_created_by' => array(
      LANGUAGE_NONE => array(
        array('target_id' => $uid)
      ),
    ),
  );

  $account = user_save(NULL, $new_user);

  // Save profile2 fields
  profile2_form_submit_build_profile($form, $form_state);
  // This is needed as some submit callbacks like user_register_submit() rely on
  // clean form values.
  profile2_form_submit_cleanup($form, $form_state);
  $profile = $form_state['profiles']['admin'];
  $profile->uid = $account->uid;
  profile2_save($profile);

  // Send email
  masterprint_mail_send_account_notify_mail('account_created_notify_for_admin', $new_user);

  drupal_set_message(t('成功添加管理员！'));
  $form_state['redirect'] = 'user/' . $user->uid . '/admin/list';
}
