<?php

/**
 * Implements hook_menu()
 */
function masterprint_admin_menu() {
  $items = array();
  $items['admin/my-salers'] = array(
  	'title' => '销售人员',
  	'description' => '查看我的销售人员',
  	'page callback' => 'list_saler',
  	'access callback' => 'user_is_client',
  );

  return $items;
}



function user_is_client() {
	global $user;

	//暂时只允许客户访问这里
	if (isset($user->roles['6']) || $user->uid == 1) {
		return TRUE;
	}
	else {
		return FALSE;
	}
}

function list_saler() {
	global $user;
	return views_embed_view('my_sale_staff', 'block');
}

/**
 *
 */


/**
 * Form used to add admin for site.
 */

