<?php

/**
 * Implements hook_menu()
 */
function masterprint_admin_menu() {
  $items = array();
  $items['admin/my-salers'] = array(
    'title' => '我的销售人员',
    'description' => '查看我的销售人员',
    'page callback' => 'list_saler',
    'access arguments' => array('administer client saler'),
  );

  $items['admin/my-salee'] = array(
    'title' => '我的经销商',
    'description' => '查看我的经销商',
    'page callback' => 'list_salee',
    'access arguments' => array('administer client supplier'),
  );

  return $items;
}

function list_saler() {
  $views_name = 'my_sale_staff';
  $display_id = 'block';

  if ($view = views_get_view($views_name)) {
    $output = $view->execute_display($display_id, array());
    if (!$view->total_rows) {
    	return t('抱歉，您暂时没有销售用户'). l('点击添加', 'admin/people/create');
    }
    return $output;
  }
}

function list_salee() {
  $views_name = 'my_sale_staff';
  $display_id = 'block_1';

  if ($view = views_get_view($views_name)) {
    $output = $view->execute_display($display_id, array());
    if (!$view->total_rows) {
    	return t('抱歉，您暂时没有经销商用户').l('点击添加', 'admin/people/create');
    }
    return $output;
  }
}

/**
 *
 */


/**
 * Form used to add admin for site.
 */

