<?php

/**
 * @file
 * Code for the masterprint_product feature.
 */

include_once 'masterprint_product.features.inc';
/**
 * Implements hook_menu()
 */
function masterprint_product_menu() {
  $items = array();
  $items['user/%user/product'] = array(
    'title' => '产品管理',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'masterprint_product_load_managed_products',
    'page arguments' => array(1),
    'access arguments' => array('manage masterprint products'),
    'weight' => 125,
  );
  $items['user/%user/product/list'] = array(
    'title' => '产品列表',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('manage masterprint products'),
  );
  $items['user/%user/product/add'] = array(
    'title' => '添加产品',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'node_add',
    'page arguments' => array('product'),
    'access arguments' => array('create', 'product'),
    'access callback' => 'node_access',
    'file path' => drupal_get_path('module', 'node'),
    'file' => 'node.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function masterprint_product_permission() {
  return array(
    'manage masterprint products' => array(
      'title' => t('Manage masterprint products'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Page callback
 */
function masterprint_product_load_managed_products($user) {
  $output= '';
  $output .= views_embed_view('product_listing', 'main_list');
  return $output;
}

/**
 *
 */
function masterprint_product_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'product_node_form') {
    $form['actions']['submit']['#submit'][] = 'masterprint_product_product_create_submit';
    $form['#validate'][] = 'masterprint_product_product_node_form_validate';
  }
}

/**
 * Custom form submission handler for #product_node_form
 */
function masterprint_product_product_create_submit($form, &$form_state) {
  global $user;
  // @todo: Do this in the views
  $form_state['redirect']  = 'user/' . $user->uid . '/product/list';
}

/**
 * Custom form submission handler for #product_node_form
 */
function masterprint_product_product_node_form_validate($form, &$form_state) {
  $values = $form_state['values'];

  // Make sure the product count is smaller that the min package num
  $product_count = !empty($values['field_product_count'][LANGUAGE_NONE][0]['value']) ?
    $values['field_product_count'][LANGUAGE_NONE][0]['value'] : 0;
  $product_min_pack_num = !empty($values['field_product_min_pack_num'][LANGUAGE_NONE][0]['value']) ?
    $values['field_product_min_pack_num'][LANGUAGE_NONE][0]['value'] : 0;

  if ($product_count < $product_min_pack_num) {
    form_set_error('field_product_count', t('产品数量不能低于最小打包数量。'));
  }

  // Make sure the serial num is unique
  $serial_number = !empty($values['field_product_serial_number']['und'][0]['value']) ?
    $values['field_product_serial_number']['und'][0]['value'] : '';
  if (!empty($serial_number)) {
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'product')
      ->fieldCondition('field_product_serial_number', 'value', $serial_number);
    $result = $query->execute();

    if (!empty($result) && empty($values['nid'])) {
      form_set_error('field_product_serial_number', t('系统已经存在与该产品序列号一样的产品。'));
    }
  }
}

/**
 * Implements hook_query_alter();
 */
function masterprint_product_views_query_alter(&$view, &$query) {
  global $user;
  if ($view->name == 'product_listing' && $view->current_display == 'main_list') {
    unset($query->where[0]);
    foreach ($query->where[1]['conditions'] as $key => $conditions) {
      if (strpos($conditions['field'], 'field_data_field_product_applied_by') !== FALSE) {
        if (user_is_client($user)) {
          $query->where[1]['conditions'][$key]['value'] = $user->uid;
        }
        else if(user_is_ae($user)) {
          $client_uids = get_clients_of_ae($user);
          $query->where[1]['conditions'][$key]['value'] = $client_uids;
          $query->where[1]['conditions'][$key]['operator'] = 'in';
        }
        else if (user_is_saler($user) || user_is_dealer($user)){
          $client = get_client_account_from_user($user);
          $query->where[1]['conditions'][$key]['value'] = $client->uid;
        }
        else {
          unset($query->where[1]['conditions'][$key]);
        }
      }
      if (strpos($conditions['field'], 'field_owned_by_ae_users__field_data_field_owned_by_ae') !== FALSE) {
        if (user_is_ae($user)) {
          $query->where[1]['conditions'][$key]['value'] = $user->uid;
        }
        else {
          unset($query->where[1]['conditions'][$key]);
        }
      }
    }
  }
  if ($view->name == 'client_listing' && $view->current_display == 'created_by_user') {
    global $user;
    if (user_is_admin($user) || $user->uid == 1) {
      unset($query->where[0]);
    }
  }
}

/**
 * Implements hook_views_pre_render()
 */
function masterprint_product_views_pre_render(&$views) {
  if ($views->human_name == 'product_listing') {
    foreach ($views->result as $key => &$row) {
      $product = node_load($row->nid);
      $row->nid = get_product_stock_number_value_on_product_list($product);
    }
  }
}
