<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function masterprint_install() {
  theme_enable(array('rubik'));
  variable_set('theme_default', 'rubik');

  variable_set('user_register', USER_REGISTER_VISITORS);

  // Enable default permissions for system roles.
  user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('access content'));
  user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('access content'));
  
  
}
