<?php

$iv = mcrypt_create_iv (mcrypt_get_block_size (MCRYPT_TripleDES, MCRYPT_MODE_CBC), MCRYPT_DEV_RANDOM);
$salt = 'master print key';

$string = json_encode(array('name' => 'admin', 'pass' => 'admin'));

/**
 * Implements hook_init()
 */
function masterprint_hash_init() {
	$hash = isset($_GET['hash']) ? $_GET['hash'] : "";

	if ($hash) {
		$hash_data = json_decode(decrypt($hash));
		dpm($hash_data);
	}
}

function encrypt($text) {
	global $salt;
    return trim(base64_encode(mcrypt_encrypt(MCRYPT_RIJNDAEL_256, $salt, $text, MCRYPT_MODE_ECB, mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_ECB), MCRYPT_RAND))));
}

function decrypt($text) {
	global $salt;
    return trim(mcrypt_decrypt(MCRYPT_RIJNDAEL_256, $salt, base64_decode($text), MCRYPT_MODE_ECB, mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_ECB), MCRYPT_RAND)));
}