<?php

/**
 * Implements hook_init()
 */
// function masterprint_login_init() {
//   global $user, $base_path;
//   if (request_uri() != $base_path .'cron.php'
//     && !$user->uid
//     && !(arg(0) == 'user'
//     && (!arg(1) || arg(1) == 'password' || arg(1) == 'register'))) {
//     if(!drupal_is_cli()){
//       drupal_set_message(t('You must login to use the system.'));
//       drupal_goto('user', array('query' => array('destination' => $_GET['q'])));
//     }
//   }
// }


/**
 * Implements hook_preprocess_page()
 */
function masterprint_global_preprocess_page(&$vars) {
  switch (current_path()) {
    case 'user/password':
      drupal_set_title(t('密码找回'));
      break;

    case 'user':
      drupal_set_title(t('User Login'));
      break;
  }
}

/**
 * Implements hook_menu()
 */


/**
 * Implements hook_form_alter()
 */
function masterprint_global_form_alter(&$form, &$form_state, $form_id) {

}

/**
 * Implements hook_preprocess_field_multiple_value_form()
 * @see: theme_field_multiple_value_form()
 */
function masterprint_theme_field_multiple_value_form($variables) {
  $element = $variables['element'];
  $output = '';

  if ($element['#cardinality'] > 1 || $element['#cardinality'] == FIELD_CARDINALITY_UNLIMITED) {
    $table_id = drupal_html_id($element['#field_name'] . '_values');
    $order_class = $element['#field_name'] . '-delta-order';
    $required = !empty($element['#required']) ? theme('form_required_marker', $variables) : '';

    $header = array(
      array(
        'data' => '<label>' . t('!title: !required', array('!title' => $element['#title'], '!required' => $required)) . "</label>",
        'class' => array('field-label'),
      ),
    );
    $rows = array();

    // Sort items according to '_weight' (needed when the form comes back after
    // preview or failed validation)
    $items = array();
    foreach (element_children($element) as $key) {
      if ($key === 'add_more') {
        $add_more_button = &$element[$key];
      }
      else {
        $items[] = &$element[$key];
      }
    }
    usort($items, '_field_sort_items_value_helper');

    // Add the items as table rows.
    foreach ($items as $key => $item) {
      $item['_weight']['#attributes']['class'] = array($order_class);
      $delta_element = drupal_render($item['_weight']);
      $cells = array(
        drupal_render($item),
      );
      $rows[] = array(
        'data' => $cells,
      );
    }

    $output = '<div class="form-item">';
    $output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => $table_id, 'class' => array('field-multiple-table'))));
    $output .= $element['#description'] ? '<div class="description">' . $element['#description'] . '</div>' : '';
    $output .= '<div class="clearfix">' . drupal_render($add_more_button) . '</div>';
    $output .= '</div>';
  }
  else {
    foreach (element_children($element) as $key) {
      $output .= drupal_render($element[$key]);
    }
  }

  return $output;
}

/**
 * Implements hook_theme_registry_alter()
 */
function masterprint_global_theme_registry_alter(&$theme_registry) {
  // Use a custom function to theme the multiple value form, disable the
  // draggable feature, and make it simple
  if (!empty($theme_registry['field_multiple_value_form'])) {
    $theme_registry['field_multiple_value_form']['function'] = 'masterprint_theme_field_multiple_value_form';
    $theme_registry['field_multiple_value_form']['theme path'] = drupal_get_path('module', 'masterprint');
  }
}
