<?php

/**
 * Implements hook_init()
 */
// function masterprint_login_init() {
//   global $user, $base_path;
//   if (request_uri() != $base_path .'cron.php'
//     && !$user->uid
//     && !(arg(0) == 'user'
//     && (!arg(1) || arg(1) == 'password' || arg(1) == 'register'))) {
//     if(!drupal_is_cli()){
//       drupal_set_message(t('You must login to use the system.'));
//       drupal_goto('user', array('query' => array('destination' => $_GET['q'])));
//     }
//   }
// }

/**
 * Implements hook_form_FORM_ID_alter()
 */
function masterprint_login_form_user_login_alter(&$form, &$form_state, $form_id) {

}

/**
 * Implements hook_preprocess_page()
 */
function masterprint_login_preprocess_page(&$vars) {
  switch (current_path()) {
    case 'user/password':
      drupal_set_title(t('密码找回'));
      break;

    case 'user':
      drupal_set_title(t('登陆入口'));
      break;
  }
}

