<?php
/**
 * @file
 * Code for the masterprint_salesman feature.
 */

include_once 'masterprint_salesman.features.inc';

/**
 * Implements hook_menu()
 */
function masterprint_salesman_menu() {
  $items = array();
  $items['user/%user/salesman'] = array(
    'title' => '客户销售人员管理',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'masterprint_salesman_load_managed_salesman',
    'page arguments' => array(1),
    'access arguments' => array('manage salesman accounts'),
    'weight' => 158,
  );
  $items['user/%user/salesman/list'] = array(
    'title' => '客户销售人员列表',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('manage salesman accounts'),
  );
  $items['user/%user/salesman/add'] = array(
    'title' => '添加客户销售人员',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('masterprint_salesman_add_salesman_form', 1),
    'access arguments' => array('manage salesman accounts'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function masterprint_salesman_permission() {
  return array(
    'manage salesman accounts' => array(
      'title' => t('Manage salesman accounts'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Form used for adding/editing an AE
 */
function masterprint_salesman_add_salesman_form($form, &$form_state, $user) {
  $form = array();

  $form['account'] = array(
    '#type' => 'fieldset',
    '#title' => t('账户信息'),
  );

  $form['account']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('用户名'),
    '#maxlength' => USERNAME_MAX_LENGTH,
    '#description' => t('Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.'),
    '#required' => TRUE,
    '#attributes' => array('class' => array('username')),
    '#default_value' => '',
  );
  $form['account']['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail地址'),
    '#maxlength' => EMAIL_MAX_LENGTH,
    '#description' => t('A valid e-mail address. All e-mails from the system will be sent to this address. The e-mail address is not made public and will only be used if you wish to receive a new password or wish to receive certain news or notifications by e-mail.'),
    '#required' => TRUE,
    '#default_value' => '',
  );
  // Password's is randomly generated, not specified by creator
  $form['account']['pass'] = array(
    '#type' => 'value',
    '#value' => user_password(mt_rand(6, 8)),
  );

  // Append the profile2 fields
  $form['profile_salesman'] = array(
    '#type' => 'fieldset',
    '#title' => t('资料信息'),
  );
  $profile = profile_create(array('type' => 'salesman'));
  $form_state['profiles']['salesman'] = $profile;
  field_attach_form('profile2', $profile, $form['profile_salesman'], $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('提交'),
  );

  return $form;
}

/**
 * Validation handler
 */
function masterprint_salesman_add_salesman_form_validate(&$form, &$form_state) {
  // Validate username.
  if (isset($form_state['values']['name'])) {
    if ($error = user_validate_name($form_state['values']['name'])) {
      form_set_error('name', $error);
    }
    else {
      $duplicate = (bool) db_select('users')
        ->fields('users', array('uid'))
        ->condition('name', db_like($form_state['values']['name']), 'LIKE')
        ->range(0, 1)
        ->execute()
        ->fetchField();

      if ($duplicate) {
        form_set_error('name', t('The name %name is already taken.', array('%name' => $form_state['values']['name'])));
      }
    }
  }

  // Trim whitespace from mail, to prevent confusing 'e-mail not valid'
  // warnings often caused by cutting and pasting.
  $mail = trim($form_state['values']['mail']);
  form_set_value($form['account']['mail'], $mail, $form_state);

  // Validate email
  if ($error = user_validate_mail($form_state['values']['mail'])) {
    form_set_error('mail', $error);
  }
  else {
    $duplicate = (bool) db_select('users')
      ->fields('users', array('uid'))
      ->condition('mail', db_like($form_state['values']['mail']), 'LIKE')
      ->range(0, 1)
      ->execute()
      ->fetchField();

    if ($duplicate) {
      form_set_error('mail', t('The e-mail address %email is already taken.', array('%email' => $form_state['values']['mail'])));
    }
  }

  // Validate profile2 fields
  if (isset($form_state['values']['profile_client'])) {
    // @see entity_form_field_validate()
    $pseudo_entity = (object) $form_state['values']['profile_client'];
    $pseudo_entity->type = 'client';
    field_attach_form_validate('profile2', $pseudo_entity, $form['profile_client'], $form_state);
  }
}

/**
 * Submission handler
 */
function masterprint_salesman_add_salesman_form_submit(&$form, &$form_state) {
  global $user;
  $uid = $user->uid;

  // Get the role id of role 'Client'
  $role_name = '客户销售人员';
  $role = user_role_load_by_name($role_name);
  $rid = $role->rid;

  // Build the user object
  $new_user = array(
    'name' => $form_state['values']['name'],
    'pass' => $form_state['values']['pass'],
    'mail' => $form_state['values']['mail'],
    'init' => $form_state['values']['mail'],
    'status' => 1,
    'access' => REQUEST_TIME,
    'roles' => array($rid => $role_name),
    'field_created_by' => array(
      LANGUAGE_NONE => array(
        array('target_id' => $uid)
      ),
    ),
  );

  $account = user_save(NULL, $new_user);
  // jackey, TODOv5.
  // if (!isset($form_state['values']['profile_client'])) {
  //   return;
  // }
  // Save profile2 fields
  profile2_form_submit_build_profile($form, $form_state);
  // This is needed as some submit callbacks like user_register_submit() rely on
  // clean form values.
  profile2_form_submit_cleanup($form, $form_state);
  $profile = $form_state['profiles']['salesman'];
  $profile->uid = $account->uid;
  profile2_save($profile);

  // Send email
  masterprint_mail_send_account_notify_mail('account_created_notify_for_client_salesman', $new_user);

  // Notify and redirect
  drupal_set_message(t('客户销售人员添加成功！'));
  $form_state['redirect'] = 'user/' . $user->uid . '/salesman/list';
}

/**
 * Display a list of all the AEs managed by the current user
 */
function masterprint_salesman_load_managed_salesman($user) {
  $output = '';
  $allowed_roles = array(
    'administrator',
    '管理员',
    'AE业务经理',
  );

  $allowed_rids = array();
  foreach ($allowed_roles as $allowed_role) {
    $role_obj = user_role_load_by_name($allowed_role);
    if (!empty($role_obj->rid)) {
      $allowed_rids[$role_obj->rid] = $role_obj->name;
    }
  }

  $user_roles = !empty($user->roles) ? $user->roles : array();
  // For admin & ae, show the whole list
  $intersection = array_intersect_key($allowed_rids, $user_roles);
  if (!empty($intersection) || $user->uid == 1) {
    $output .= views_embed_view('salesman_listing', 'total_summary', $user->uid);
  }
  // Otherwise, show part of the list
  else {
    $output .= views_embed_view('salesman_listing', 'client_summary', $user->uid);
  }
  return $output;
}

/**
 * Implements hook_form_alter()
 */
function masterprint_salesman_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'masterprint_user_edit_own_profile2') {
    $profile_type = @$form['profile_type']['#value'];
    global $user;
    $can_not_access = user_is_dealer($user) || user_is_saler($user) || user_is_client($user);
    //经销商
    if ($profile_type == 'dealer' && $can_not_access) {
      $form['profile_dealer']['field_dealer_client_owner']['#access'] = FALSE;
    }
    if ($profile_type == 'salesman' && $can_not_access) {
      $form['profile_salesman']['field_salesman_client_owner']['#access'] = FALSE;
    }
  }
}
